# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nish's Blog
tagline:          Home
url:              http://web.stanford.edu/~nishith/
baseurl:          /

author:
  name:           'Nishith Khandwala'
  url:            https://twitter.com/nishith_bsk

gems: [jekyll-paginate, jekyll-gist]
paginate:         5

# Custom vars
github:
  repo:           https://github.com/nishithbsk/nishith.github.io
